server:
  port: 8080

spring:
  datasource:
    # 指向你刚建的库 automax_car_mall
    url: jdbc:mysql://${DB_HOST:172.26.160.1}:${DB_PORT:3306}/${DB_NAME:automax_car_mall}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: ${DB_USER:root}
    password: ${DB_PASS:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis-Plus 进阶配置
mybatis-plus:
  configuration:
    # 在控制台打印 SQL 语句，调试必备，防止“盲打”
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名转换（数据库 vin_code 自动映射 Java 的 vinCode）
    map-underscore-to-camel-case: true
